require("dotenv").config();
const express = require("express");
const app = express();
const PORT = process.env.PORT || 5000;
const routes = require("../talon_events/be/routes");
const router = routes(app);
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use("/api", router);
app.listen(PORT, () => console.log(`listening at http://localhost:${PORT}`));
